OPTS=

all: probe_IDs FrequencySnapshot_IDs TimeSnapshot_IDs

probe_IDs: probe_IDs.pas
	fpc $(OPTS) probe_IDs.pas

FrequencySnapshot_IDs: FrequencySnapshot_IDs.pas
	fpc $(OPTS) FrequencySnapshot_IDs.pas

TimeSnapshot_IDs: TimeSnapshot_IDs.pas
	fpc $(OPTS) TimeSnapshot_IDs.pas

clean:
	rm -f *.o probe_IDs FrequencySnapshot_IDs TimeSnapshot_IDs
