OPTS=-Fu/usr/local/languages/fpc-2.4.0/lib/fpc/2.4.0/units/x86_64-linux/rtl/

all: probe_IDs FrequencySnapshot_IDs TimeSnapshot_IDs

probe_IDs:
	fpc $(OPTS) probe_IDs.pas

FrequencySnapshot_IDs:
	fpc $(OPTS) FrequencySnapshot_IDs.pas

TimeSnapshot_IDs:
	fpc $(OPTS) TimeSnapshot_IDs.pas

clean:
	rm -f *.o probe_IDs FrequencySnapshot_IDs TimeSnapshot_IDs
