OPTS=

all: probe_IDs FrequencySnapshot_IDs TimeSnapshot_IDs

probe_IDs:
	fpc $(OPTS) probe_IDs.pas

FrequencySnapshot_IDs:
	fpc $(OPTS) FrequencySnapshot_IDs.pas

TimeSnapshot_IDs:
	fpc $(OPTS) TimeSnapshot_IDs.pas

clean:
	rm -f *.o probe_IDs FrequencySnapshot_IDs TimeSnapshot_IDs
